name: 'failure Slack message'
description: 'Sends a Slack message to notify of failure'
inputs:
  title:
    description: "Title of the failed workflow"
    required: true
  channel_id:
    description: "Slack channel to send to"
    required: true
  SLACK_BOT_TOKEN:
    description: "Slack bot token with chat:write permission"
    required: true

runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@v2.1.0
      with:
        token: ${{ inputs.SLACK_BOT_TOKEN }}
        method: chat.postMessage
        payload: |
          {
            "channel": "${{ inputs.channel_id }}",
            "text": ":no_entry: *${{ inputs.title }}* — Workflow *${{ github.workflow }}* failed!",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":no_entry: Github Workflow *${{ github.workflow }}* failed"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Workflow:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:* `${{ github.repository }}`"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Job:* `${{ github.job }}`"
                  }
                ]
              }
            ]
          }