name: Playwright Tests PR
on:
  pull_request:
    paths:
      - '**.ts'
    paths-ignore:
      - 'performance/**'

jobs:
  test:
    name: Integration tests
    uses: ./.github/workflows/playwright.yml
    secrets: inherit
    with:
      environment: test
