name: Dev - Integration tests
on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Repo triggering tests'
        required: false
        default: 'all'
        type: string
      branch:
        description: 'Feature branch'
        required: false
        default: 'main'
        type: string
  schedule:
    - cron: '00 7 * * 1-5' # At 07:00 AM, Monday through Friday
jobs:
  trigger_deploy:
    name: Trigger deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          app-id: ${{ secrets.INTEGRATION_TESTS_TRIGGER_APP_ID }}
          private-key: ${{ secrets.INTEGRATION_TESTS_TRIGGER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-actions: write
          repositories: hmpps-arns-assessment-platform-ui
      - name: Deploy to env
        uses: actions/github-script@v9
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'hmpps-arns-assessment-platform-ui',
              workflow_id: 'deploy_to_env.yml',
              ref: 'main'
            })
      - name: Sleep for 5 mins
        run: sleep 300s
        shell: bash
  send-notification:
    name: Integration tests
    needs: trigger_deploy
    uses: ./.github/workflows/playwright.yml
    with:
      channel_id: ${{ vars.INTEGRATION_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      environment: dev
      source: ${{ inputs.source || 'all' }}
      branch: ${{ inputs.branch || 'main' }}
    secrets: inherit
