name: Ephemeral Integration tests
on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Repo triggering tests'
        required: false
        default: 'all'
        type: string
      url:
        description: 'Ephemeral url'
        required: false
        default: 'https://google.com'
        type: string

jobs:
  int-tests:
    name: Integration tests
    uses: ./.github/workflows/playwright.yml
    with:
      channel_id: 'NO_SLACK'
      environment: dev
      source: ${{ inputs.source || 'all' }}
      url: ${{ inputs.url || 'https://google.com' }}
    secrets: inherit
