name: Integration tests
on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Repo triggering tests'
        required: false
        default: 'all'
        type: string
  schedule:
    - cron: '45 7 * * 1-5'
jobs:
  send-notification:
    name: Integration tests
    uses: ./.github/workflows/playwright.yml
    with:
      channel_id: ${{ vars.INTEGRATION_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      environment: test
      source: ${{ inputs.source }}
    secrets: inherit